[package]
name = "stalch"
version = "0.2.0"
authors = ["LFalch <lucas@wasd.dk>"]
description = "stack-based esolang"
edition = "2018"

[dependencies]
clap = { version = ">=2.26, <=2.32", optional = true }

[[bin]]
name = "stalch"
doc = false
required-features = ["clap"]

[features]
debug = []
